import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "./providers";


const inter = Inter({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
          <TooltipProvider>
            <Providers>
              {children}
            </Providers>
            <Toaster/>
          </TooltipProvider>
        </body>
    </html>
  );
}
